spring:
  data:
    mongodb:
      database: development
      authentication-database: admin
      username: ENC(htKW1daMWkcNDaMgpz5tMQ==)
      password: ENC(4OquGYQUnDpLv8+JDxtxwocRvj/Ewr+nMerRk+2IdXI=)
      port: 27018
      host: img-c.tech
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://img-c.tech:8084/auth/realms/img-c/protocol/openid-connect/token
            authorization-uri: https://img-c.tech:8084/auth/realms/img-c/protocol/openid-connect/auth
            userinfo-uri: https://img-c.tech:8084/auth/realms/img-c/protocol/openid-connect/userinfo
            jwk-set-uri: https://img-c.tech:8084/auth/realms/img-c/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: 8d552c98-3d3b-420e-823d-988458e0a7f6
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: https://img-c.tech:8084/auth/realms/img-c/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://dev-reg:8080/eureka/
