spring:
  data:
    mongodb:
      database: development
      authentication-database: admin
      username: ENC(htKW1daMWkcNDaMgpz5tMQ==)
      password: ENC(bpLBdSpa6KWokh5nFJTnP41bHLuoVaHzGOoCTfiKtjs=)
      port: 27017
      host: img-c.tech
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://img-c.tech:8084/auth/realms/img-c_prod/protocol/openid-connect/token
            authorization-uri: https://img-c.tech:8084/auth/realms/img-c_prod/protocol/openid-connect/auth
            userinfo-uri: https://img-c.tech:8084/auth/realms/img-c_prod/protocol/openid-connect/userinfo
            jwk-set-uri: https://img-c.tech:8084/auth/realms/img-c_prod/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: 65e7b935-c687-4673-9c8a-fba80e01e29e
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: https://img-c.tech:8084/auth/realms/img-c_prod/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://prod-reg:8080/eureka/
